### ISSUE TITLE
Missing instructions on running local tests

### ISSUE THREAD

**Issue by jenjiyi** [learn-co-students/js-functions-lab-v-000#136] opened 2016-08-02 18:05 UTC
I believe the order of labs is off here if tests are required on this one. I followed instructions from the next lesson . When I type "Learn" in my terminal I get "This directory doesn't appear to have any specs in it." I'll raise an issue in that one if it persists.

I installed mocha and added in the missing node dependencies that are in the head of the index.html file and was able to view tests in my browser. 
<script src="node_modules/mocha/mocha.js"></script> <script src="node_modules/expect/umd/expect.min.js"></script>
I don't think installation was covered in the material so far or it should be added to the readme for this lab.

Then I submitted a pull request even though I can't complete the local test step.

**Comment by deniznida** [comment] 2016-09-13 14:43
@aturkewi & @AnnJohn 👀 ^^

**Comment by aturkewi** [comment] 2016-09-13 19:15
Hey @jenjiyi it looks like this issue was already resolved in the conical version of this lab: https://github.com/learn-co-curriculum/js-functions-lab/issues/9

@deniznida I'm not sure I see what the issue is. When I run `learn` I get:

```
[19:09:57] (master) js-functions-lab-v-000                                              
// ♥ learn                                                                              
                                                                                        
> js-functions-lab@0.1.0 test /home/aturkewi/code/labs/js-functions-lab-v-000           
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json                     
                                                                                        
 0   -_,------,                                                                         
 4   -_|   /\_/\                                                                        
 0   -^|__( x .x)                                                                       
     -
                                                                                        
  0 passing (2s)                                                                        
  4 failing                                                                             
                                                                                        
  1) functions happyHolidays returns "Happy holidays!":                                 
     ReferenceError: happyHolidays is not defined                                       
      at Context.it (test/index-test.js:6:14)                                           
                                                                                        
  2) functions happyHolidaysTo(name) returns "Happy holidays, ${name}!":                
     ReferenceError: happyHolidaysTo is not defined                                     
      at Context.it (test/index-test.js:12:14)                                          
                                                             
  3) functions happyHolidayTo(holiday, name) returns "Happy ${holiday}, ${name}!":      
     ReferenceError: happyHolidayTo is not defined                                      
      at Context.it (test/index-test.js:18:14)                                          
                                                                                        
  4) functions holidayCountdown(holiday, days) returns "It's ${days} until ${holiday}!":
     ReferenceError: holidayCountdown is not defined                                    
      at Context.it (test/index-test.js:24:14)                                          
                                                                                        
                                                                                        
                                                                                        
npm ERR! Test failed.  See above for more details.             
```

If you're seeing something else though, can you open a new issue on https://github.com/learn-co-curriculum/js-functions-lab

**Closed by aturkewi** 2016-09-13 19:15 UTC
